# Generated by Django 5.0.1 on 2024-01-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0002_pereval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pereval',
        ),
    ]
